openapi: 3.0.3
info:
  title: Bsale back
  description: Api para prueba de bsale
  version: 1.0.0
servers:
  - url: https://leodreco-bsale-back.herokuapp.com
    description: Api
  - url: http://localhost:3000
    description: Local
components:
  schemas:
    FilterObject:
      type: object # Se tiene que convertir a string con JSON.stringify
      properties:
        filters:
          type: object
          minProperties: 1
          properties:
            name:
              type: object
              description: 'name es el nombre del campo a filtrar, se puede reemplazar con los nombres de campos a filtrar'
              properties:
                value:
                  type: string
                  description: Valor a buscar
                  example: bebida
                matchMode:
                  type: string
                  description: Manera en que se realizara la busqueda
                  enum:
                    - contains
                    - endsWith
                    - equals
                    - gt
                    - gte
                    - in
                    - lt
                    - lte
                    - not
                    - notIn
                    - startsWith
                  example: startsWith
        sortField:
          type: string
          description: 'Campo por el que se ordenara la data'
          example: id
        sortOrder:
          type: string
          description: 'Indica si el orden sera ASC o DESC, default ASC'
          enum:
            - desc
            - asc
          example: asc
    SuccessResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: array
          items:
            type: object
        message:
          type: string
        totalRows:
          type: integer
          example: 57
    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
      example:
        success: false
        message: Error
    CategoryModel:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      example:
        id: 1
        name: bebida energetica
    ProductModel:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        url_image:
          type: string
        price:
          type: number
        discount:
          type: integer
        category:
          type: integer
      example:
        id: 1
        name: ENERGETICA MR BIG
        url_image: "https://dojiw2m9tvv09.cloudfront.net/11132/product/misterbig3308256.jpg"
        price: 1490
        discount: 20
        category: 1
  parameters:
    FilterParam:
      name: filters
      in: query
      description: 'Este objeto tiene que mandarse como string con JSON.stringify()'
      required: false
      schema:
        $ref: '#/components/schemas/FilterObject'
    SkipParam:
      name: skip
      description: 'Indica a partir de que registro se traerá información'
      in: query
      schema:
        type: integer
        example: 0
    TakeParam:
      name: take
      description: 'Indica cuantos registros se traerán en la response'
      in: query
      schema:
        type: integer
        example: 12
paths:
  /api/category:
    get: 
      description: Listado de categorias
      parameters:
        - $ref: "#/components/parameters/FilterParam"
        - $ref: "#/components/parameters/SkipParam"
        - $ref: "#/components/parameters/TakeParam"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/SuccessResponse'
                properties:              
                  data:
                    items:
                      $ref: '#/components/schemas/CategoryModel'
        400:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/product:
    get: 
      description: Listado de productos
      parameters:
        - $ref: "#/components/parameters/FilterParam"
        - $ref: "#/components/parameters/SkipParam"
        - $ref: "#/components/parameters/TakeParam"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/SuccessResponse'
                properties:
                  data:
                    items:
                      $ref: '#/components/schemas/ProductModel'
        400:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
